# 配置数据连接
spring:
# ===================================================================
# datasource配置
# ===================================================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://northsailor.mysql.rds.aliyuncs.com:3306/tmooc_work?useSSL=false&useUnicode=true&character_set_server=utf8mb4
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Hjq910314
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: com.tmooc.work.config.MySQL5InnoDBDialectUtf8mb4
    open-in-view: true
    properties:
      hibernate:
        dialect: com.tmooc.work.config.MySQL5InnoDBDialectUtf8mb4
# ===================================================================
# redis配置
# ===================================================================
  redis:
    host: 39.107.98.120
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  resources:
    add-mappings: true
    cache-period: 3600
    static-locations: classpath:/static/
    chain:
      cache: true
      enabled: true
      gzipped: true
      html-application-cache: true
# ===================================================================
# batch配置
# ===================================================================
  batch:
    job:
      enabled: false
      names: null
server:
  port: 8080

# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 140.143.0.246:22122
